Update/Reminder mail notification for enrolled teachers
linkstreet/moodle-mod_zoom pull request #19
Opened 2020-09-10 05:13 UTC by nayanalinkstreet

@meyyappanv @Naveen1895 Request you to review the code.

2020-09-10 06:57 UTC, Naveen1895 commented
@nayanalinkstreet From the next PR onwards, Could you follow branch naming conventions  **"<type of task>/<short-desciption-of-task-separated-by-hypens>**" ?

2020-09-10 07:06 UTC, Naveen1895 requested changes

2020-09-10 07:06 UTC, Naveen1895 commented on locallib.php
> +    									);
@nayanalinkstreet Could you format this ?

2020-09-10 07:06 UTC, Naveen1895 commented on mod_form.php
> +        //Enable mail notifications for teachers
@nayanalinkstreet I feel this will be good if you bring the whole option below the remainder mail checkbox

2020-09-10 12:32 UTC, Naveen1895 commented
@nayanalinkstreet Can you increase the zoom plugin version?

2020-09-10 12:39 UTC, Naveen1895 commented on version.php
>  $plugin->release = 'v2.4.1';
@nayanalinkstreet Could you make it as 2.5.0?

2020-09-10 13:18 UTC, Naveen1895 approved these changes

2020-09-11 12:01 UTC, meyyappanv approved these changes

2020-09-11 12:01 UTC, merged